openapi: 3.0.0
info:
  title: Contacts API
  description: API for managing contacts
  version: 1.0.0
servers:
  - url: https://contacts-reader-backend-7k84.onrender.com

paths:
  /api/contacts:
    get:
      summary: Get list of contacts
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Contact"

  /api/contacts/:id:
    get:
      summary: Get contact by ID
      parameters:
        - name: id
          in: path
          required: true
          description:  Unique identifier of the contact
          schema:
            type: string

      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"
        "404":
          description: Not Found

components:
  schemas:
    Contact:
      type: object
      properties:
        _id:
          type: string
          description: Unique contact ID
        name:
          type: string
          description: Contact name
        email:
          type: string
          description: Contact email
        phone:
          type: string
          description: Contact phone
        # favorite:
        #   type: boolean
        #   description: Favorite Contact

      required:
        - name
