openapi: 3.0.0
info:
  title: Contacts API
  description: API for managing contacts
  version: 1.0.0
servers:
  - url: https://contacts-reader-backend-7k84.onrender.com

paths:
  /api/contacts:
    get:
      tags:
        - Contacts
      summary: Get list of contacts
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Contact"

    post:
      tags:
        - Contacts
      summary: Create a new contact
      requestBody:
          description: New Contact Information
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContactInput"
      responses:
            "201":
              description: Contact created successfully
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Contact"
            "400":
              description: Invalid Input

  /api/contacts/{id}:
    get:
      tags:
        - Contacts
      summary: Get contact by ID
      parameters:
        - name: contactId
          in: path
          required: true
          description:  Unique identifier of the contact
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"
        "404":
          description: Not Found
          
    delete:
      tags:
        - Contacts
      summary: Delete contact by ID
      parameters:
        - name: contactId
          in: path
          required: true
          description:  Unique identifier of the contact
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"
        "404":
          description: Not Found

components:
  schemas:
    Contact:
      type: object
      properties:
        _id:
          type: string
          description: Unique contact ID
        name:
          type: string
          description: Contact name
        email:
          type: string
          description: Contact email
        phone:
          type: string
          description: Contact phone
        favorite:
          type: boolean
          description: Favorite Contact

      required:
        - name
        - email
        - phone

    ContactInput:
      type: object
      properties:
        name:
          type: string
          description: Contact name
        email:
          type: string
          description: Contact email
        phone:
          type: string
          description: Contact phone
          
      required:
        - name
        - email
        - phone

